.TH "rfs_nss_ctl" "1" "0.10" "remotefs" "remotefs"
.SH "NAME"
rfs_nss \- remotefs server for id-mapping
.SH "SYNOPSIS"
\fBrfs\fR start | stop | check

.SH "OPTIONS"
.PP
\fB\start\fR start rfs_nss if it is not running, otherwise tell rfs_nss that a
further client is started
.br
\fB\stop\fR tell rfs_nfs that a client stop, if all clients are stpped, rfs_nss
will terminate
.RE
.PP
.SH "DESCRIPTION"
rfs_nss_ctrl is a help tool for starting and stopping rfs_nss
.SH "AUTHORS"
.PP
Jean\-Jacques Sarton: jjsarton@users.sourceforge.net
.SH "REPORTING BUGS"
.PP
See remotefs project on SourceForge: http://remotefs.sourceforge.net/
.SH "COPYING"
GNU General Public License (GPL) 
.SH "SEE ALSO"
.PP
\fBrfsd\fR(8), \fBrfspasswd\fR(8) \fBrfs\fR(1) \fBrfsd\fR(8)\fBnsswitch.conf\fR(5)
\fBrfs_nss\fr(1).
