.TH "rfs_nss" "1" "0.10" "remotefs" "remotefs"
.SH "NAME"
rfs_nss \- remotefs server for id-mapping
.SH "SYNOPSIS"
\fBrfs\fR [-l] [-f] [-e|-s host]

.SH "OPTIONS"
.PP
\fB\-l\fR print log on the terminal.
.br
\fB\-f\fR start in foreground.
.br
\fB\-e host\fR End rfs_nss
.br
\fB\-s host\fR start rfs_nss
.RE

.PP
.SH "DESCRIPTION"
rfs_nss is a little server which must run on the remotefs client.
.PP
On Unix systeme users and groups are identified by a uid or a gid.
Remotefs use user name and group name in order to identify the user
or group and not the uid or gid.
.PP
rfs_nss get queries for uid or gid and return, if the name is not
known an id which value depend from the queried name.
This happen if you mount a remotefs duerectory and if the user or group
name is unknown.
.PP
This feature allow you, for example, to see the owner of a file, even
if the user is not known on your system.
.PP
If you change the ownership of a file or directory you must
be shure that the user or group is well knowm on the target system.
.PP
Rfs_nfs is normally started by an rfs client, if an instance is
allready running, rfs_nss send a message to the allready started
processes so that the number of client is known.
.PP
At the start rfs_nss query the given client for the user and group
name known by the server \fB\host\fR and assign for each user and
group an unique uid / gid.
.PP
The user and group names are appended with \fB\@host\fR. If 
host is an IP address, rfs_nss try to convert it to an name.
.PP
After the termination of the last rfs client, rfs_nss will
terminate.
.PP
The file /etc/nsswitch.conf must be modified in order to
use this feature. The line beginning with \fBpasswd:\fR and
\fBgroup:\fR must contain as last entry \fBrfs\fR.
.SH "AUTHORS"
.PP
Jean\-Jacques Sarton: jjsarton@users.sourceforge.net
.SH "REPORTING BUGS"
.PP
See remotefs project on SourceForge: http://remotefs.sourceforge.net/
.SH "COPYING"
GNU General Public License (GPL) 
.SH "SEE ALSO"
.PP
\fBrfsd\fR(8), \fBrfspasswd\fR(8) \fBrfs\fR(1) \fBnsswitch.conf\fR(5) \fBrfs_nss\fr(1).
