.TH "rfs_nss_get" "1" "0.10" "remotefs" "remotefs"
.SH "NAME"
rfs_nss_get \- client for id-mapping.
.SH "SYNOPSIS"
\fBrfs\fR -h|H host_name_or_ip [-p port]

.SH "OPTIONS"
.PP
\fB\-h\fR IP address or name of the server rfs_nss_rem.
.br
\fB\-H\fR IP address or name of the server rfs_nss_rem, add also the host name to the names
.br
\fB\-n\ name fR set host name to name (to be used with option -h)
.br
\fB\-a\fR add all user/group name, even if allready provided on the system.
.br
\fB\-p\fR port to use for communication, default 5004.
.RE

.PP
.SH "DESCRIPTION"
rfs_nss_get ask rfs_nss_rem for the users or groups known on the server and add them to
the database hold by rfs_nss.
.PP
You will be able to "synchronize" the remotefs client with the remotefs server,

.SH "AUTHORS"
.PP
Jean\-Jacques Sarton: jjsarton@users.sourceforge.net
.SH "REPORTING BUGS"
.PP
See remotefs project on SourceForge: http://remotefs.sourceforge.net/
.SH "COPYING"
GNU General Public License (GPL) 
.SH "SEE ALSO"
.PP
\fBrfsd\fR(8), \fBrfspasswd\fR(8) \fBrfs\fR(1) \fBnsswitch.conf\fR(5) \fBrfs_nss\fr(1).
\fBrfs_nss_rem\fr(1)
