CC = gcc
LDFLAGS = -lcrypt
TARGET = rfspasswd

OBJS = src/rfspasswd.o \
src/passwd.o \
src/crypt.o \
src/list.o \
src/buffer.o \
src/alloc.o

default: $(OBJS) link_passwd
	ln -sf bin/$(TARGET) $(TARGET)

link_passwd:
	$(CC) $(OBJS) $(LDFLAGS) -o bin/$(TARGET)

%.o : %.c
	$(CC) -c $(CFLAGS) -Wall $< -o $@

clean:
	rm -f bin/$(TARGET) $(TARGET)
	rm -f src/*.o
	rm -f $(TARGET)
	