src/acl_utils.o:src/acl_utils.h
src/acl_utils.o:src/buffer.h
src/acl_utils.o:src/config.h
src/acl_utils.o:src/id_lookup.h
src/acl_utils.o:src/instance.h
src/acl_utils.o:src/list.h
src/acl_utils.o:src/acl/libacl/byteorder.h
src/attr_cache.o:src/attr_cache.h
src/attr_cache.o:src/buffer.h
src/attr_cache.o:src/config.h
src/attr_cache.o:src/instance_client.h
src/attr_cache.o:src/ratio.h
src/buffer.o:src/buffer.h
src/buffer.o:src/config.h
src/buffer.o:src/inet.h
src/cleanup.o:src/buffer.h
src/cleanup.o:src/config.h
src/cleanup.o:src/instance_server.h
src/cleanup.o:src/list.h
src/command.o:src/command.h
src/command.o:src/config.h
src/crypt.o:src/config.h
src/crypt.o:src/crypt.h
src/crypt.o:src/md5crypt/crypt_md5.h
src/data_cache.o:src/buffer.h
src/data_cache.o:src/config.h
src/data_cache.o:src/data_cache.h
src/data_cache.o:src/list.h
src/error.o:src/compat.h
src/error.o:src/error.h
src/error.o:src/inet.h
src/exports.o:src/buffer.h
src/exports.o:src/config.h
src/exports.o:src/exports.h
src/exports.o:src/list.h
src/exports.o:src/utils.h
src/fuse_rfs.o:src/config.h
src/fuse_rfs.o:src/fuse_rfs.h
src/fuse_rfs.o:src/operations_rfs.h
src/fuse_rfs.o:src/operations_sync.h
src/id_lookup.o:src/config.h
src/id_lookup.o:src/id_lookup.h
src/id_lookup.o:src/buffer.h
src/id_lookup.o:src/list.h
src/id_lookup_client.o:src/config.h
src/id_lookup_client.o:src/id_lookup_client.h
src/instance.o:src/config.h
src/instance.o:src/instance.h
src/instance_client.o:src/config.h
src/instance_client.o:src/instance_client.h
src/instance_server.o:src/config.h
src/instance_server.o:src/instance.h
src/instance_server.o:src/instance_server.h
src/keep_alive_client.o:src/config.h
src/keep_alive_client.o:src/instance_client.h
src/keep_alive_server.o:src/config.h
src/keep_alive_server.o:src/instance_server.h
src/list.o:src/buffer.h
src/list.o:src/config.h
src/list.o:src/list.h
src/names.o:src/buffer.h
src/names.o:src/config.h
src/names.o:src/names.h
src/nss_client.o:src/buffer.h
src/nss_client.o:src/command.h
src/nss_client.o:src/config.h
src/nss_client.o:src/list.h
src/nss_client.o:src/names.h
src/nss_server.o:src/buffer.h
src/nss_server.o:src/command.h
src/nss_server.o:src/config.h
src/nss_server.o:src/instance_client.h
src/nss_server.o:src/list.h
src/nss_server.o:src/nss_server.h
src/nss_server.o:src/sendrecv.h
src/operations.o:src/attr_cache.h
src/operations.o:src/buffer.h
src/operations.o:src/command.h
src/operations.o:src/compat.h
src/operations.o:src/config.h
src/operations.o:src/data_cache.h
src/operations.o:src/id_lookup_client.h
src/operations.o:src/inet.h
src/operations.o:src/instance_client.h
src/operations.o:src/list.h
src/operations.o:src/names.h
src/operations.o:src/operations.h
src/operations.o:src/operations_rfs.h
src/operations.o:src/path.h
src/operations.o:src/resume.h
src/operations.o:src/sendrecv.h
src/operations_acl.o:src/config.h
src/operations_acl.o:src/command.h
src/operations_acl.o:src/buffer.h
src/operations_acl.o:src/acl_utils.h
src/operations_acl.o:src/instance_client.h
src/operations_acl.o:src/sendrecv.h
src/operations_acl.o:src/operations_rfs.h
src/operations_exports.o:src/buffer.h
src/operations_exports.o:src/command.h
src/operations_exports.o:src/config.h
src/operations_exports.o:src/instance_client.h
src/operations_exports.o:src/operations_rfs.h
src/operations_exports.o:src/sendrecv.h
src/operations_exports.o:src/utils.h
src/operations_links.o:src/attr_cache.h
src/operations_links.o:src/buffer.h
src/operations_links.o:src/command.h
src/operations_links.o:src/config.h
src/operations_links.o:src/instance_client.h
src/operations_links.o:src/list.h
src/operations_links.o:src/operations_rfs.h
src/operations_links.o:src/sendrecv.h
src/operations_nss.o:src/buffer.h
src/operations_nss.o:src/command.h
src/operations_nss.o:src/config.h
src/operations_nss.o:src/instance_client.h
src/operations_nss.o:src/list.h
src/operations_nss.o:src/operations_rfs.h
src/operations_nss.o:src/sendrecv.h
src/operations_read.o:src/buffer.h
src/operations_read.o:src/command.h
src/operations_read.o:src/config.h
src/operations_read.o:src/data_cache.h
src/operations_read.o:src/instance_client.h
src/operations_read.o:src/keep_alive_client.h
src/operations_read.o:src/list.h
src/operations_read.o:src/operations.h
src/operations_read.o:src/operations_rfs.h
src/operations_read.o:src/psemaphore.h
src/operations_read.o:src/ratio.h
src/operations_read.o:src/resume.h
src/operations_read.o:src/sendrecv.h
src/operations_rfs.o:src/attr_cache.h
src/operations_rfs.o:src/buffer.h
src/operations_rfs.o:src/command.h
src/operations_rfs.o:src/config.h
src/operations_rfs.o:src/crypt.h
src/operations_rfs.o:src/id_lookup.h
src/operations_rfs.o:src/instance_client.h
src/operations_rfs.o:src/keep_alive_client.h
src/operations_rfs.o:src/list.h
src/operations_rfs.o:src/nss_server.h
src/operations_rfs.o:src/operations.h
src/operations_rfs.o:src/operations_rfs.h
src/operations_rfs.o:src/resume.h
src/operations_rfs.o:src/sendrecv.h
src/operations_rfs.o:src/sockets.h
src/operations_rfs.o:src/ssl_client.h
src/operations_sync.o:src/instance.h
src/operations_sync.o:src/keep_alive_client.h
src/operations_sync.o:src/operations.h
src/operations_sync.o:src/operations_rfs.h
src/operations_write.o:src/attr_cache.h
src/operations_write.o:src/buffer.h
src/operations_write.o:src/command.h
src/operations_write.o:src/config.h
src/operations_write.o:src/data_cache.h
src/operations_write.o:src/instance_client.h
src/operations_write.o:src/keep_alive_client.h
src/operations_write.o:src/list.h
src/operations_write.o:src/operations.h
src/operations_write.o:src/operations_rfs.h
src/operations_write.o:src/psemaphore.h
src/operations_write.o:src/sendrecv.h
src/passwd.o:src/buffer.h
src/passwd.o:src/config.h
src/passwd.o:src/list.h
src/passwd.o:src/passwd.h
src/path.o:src/config.h
src/resume.o:src/buffer.h
src/resume.o:src/config.h
src/resume.o:src/instance_client.h
src/resume.o:src/list.h
src/resume.o:src/resume.h
src/rfs.o:src/buffer.h
src/rfs.o:src/config.h
src/rfs.o:src/crypt.h
src/rfs.o:src/fuse_rfs.h
src/rfs.o:src/id_lookup.h
src/rfs.o:src/instance_client.h
src/rfs.o:src/operations_rfs.h
src/rfs.o:src/passwd.h
src/rfs.o:src/sug_client.h
src/rfsd.o:src/config.h
src/rfsd.o:src/exports.h
src/rfsd.o:src/instance_server.h
src/rfsd.o:src/keep_alive_server.h
src/rfsd.o:src/passwd.h
src/rfsd.o:src/rfsd.h
src/rfsd.o:src/server.h
src/rfsd.o:src/signals_server.h
src/rfsd.o:src/sockets.h
src/rfsd.o:src/sug_server.h
src/rfspasswd.o:src/config.h
src/rfspasswd.o:src/crypt.h
src/rfspasswd.o:src/passwd.h
src/rfspasswd.o:src/signals.h
src/sendrecv.o:src/command.h
src/sendrecv.o:src/config.h
src/sendrecv.o:src/error.h
src/sendrecv.o:src/instance.h
src/sendrecv.o:src/ssl.h
src/server.o:src/buffer.h
src/server.o:src/command.h
src/server.o:src/config.h
src/server.o:src/cleanup.h
src/server.o:src/exports.h
src/server.o:src/id_lookup.h
src/server.o:src/instance_server.h
src/server.o:src/keep_alive_server.h
src/server.o:src/passwd.h
src/server.o:src/sendrecv.h
src/server.o:src/server.h
src/server.o:src/server_handlers_sync.h
src/server_handlers.o:src/buffer.h
src/server_handlers.o:src/command.h
src/server_handlers.o:src/config.h
src/server_handlers.o:src/cleanup.h
src/server_handlers.o:src/exports.h
src/server_handlers.o:src/id_lookup.h
src/server_handlers.o:src/inet.h
src/server_handlers.o:src/instance_server.h
src/server_handlers.o:src/list.h
src/server_handlers.o:src/passwd.h
src/server_handlers.o:src/path.h
src/server_handlers.o:src/sendrecv.h
src/server_handlers.o:src/server.h
src/server_handlers_acl.o:src/acl_utils.h
src/server_handlers_acl.o:src/buffer.h
src/server_handlers_acl.o:src/command.h
src/server_handlers_acl.o:src/config.h
src/server_handlers_acl.o:src/instance_server.h
src/server_handlers_acl.o:src/server.h
src/server_handlers_acl.o:src/sendrecv.h
src/server_handlers_exports.o:src/buffer.h
src/server_handlers_exports.o:src/command.h
src/server_handlers_exports.o:src/config.h
src/server_handlers_exports.o:src/exports.h
src/server_handlers_exports.o:src/instance_server.h
src/server_handlers_exports.o:src/list.h
src/server_handlers_exports.o:src/sendrecv.h
src/server_handlers_exports.o:src/server.h
src/server_handlers_links.o:src/buffer.h
src/server_handlers_links.o:src/command.h
src/server_handlers_links.o:src/config.h
src/server_handlers_links.o:src/instance_server.h
src/server_handlers_links.o:src/sendrecv.h
src/server_handlers_links.o:src/server.h
src/server_handlers_nss.o:src/buffer.h
src/server_handlers_nss.o:src/config.h
src/server_handlers_nss.o:src/command.h
src/server_handlers_nss.o:src/id_lookup.h
src/server_handlers_nss.o:src/instance_server.h
src/server_handlers_nss.o:src/list.h
src/server_handlers_nss.o:src/sendrecv.h
src/server_handlers_nss.o:src/server.h
src/server_handlers_read.o:src/buffer.h
src/server_handlers_read.o:src/command.h
src/server_handlers_read.o:src/config.h
src/server_handlers_read.o:src/instance_server.h
src/server_handlers_read.o:src/sendrecv.h
src/server_handlers_read.o:src/server.h
src/server_handlers_rfs.o:src/buffer.h
src/server_handlers_rfs.o:src/command.h
src/server_handlers_rfs.o:src/config.h
src/server_handlers_rfs.o:src/crypt.h
src/server_handlers_rfs.o:src/exports.h
src/server_handlers_rfs.o:src/id_lookup.h
src/server_handlers_rfs.o:src/instance_server.h
src/server_handlers_rfs.o:src/list.h
src/server_handlers_rfs.o:src/passwd.h
src/server_handlers_rfs.o:src/sockets.h
src/server_handlers_rfs.o:src/utils.h
src/server_handlers_rfs.o:src/server.h
src/server_handlers_rfs.o:src/sendrecv.h
src/server_handlers_rfs.o:src/ssl_server.h
src/server_handlers_sync.o:src/keep_alive_server.h
src/server_handlers_sync.o:src/server_handlers.h
src/server_handlers_write.o:src/buffer.h
src/server_handlers_write.o:src/command.h
src/server_handlers_write.o:src/config.h
src/server_handlers_write.o:src/instance_server.h
src/server_handlers_write.o:src/list.h
src/server_handlers_write.o:src/sendrecv.h
src/server_handlers_write.o:src/server.h
src/signals.o:src/signals.h
src/signals_client.o:src/config.h
src/signals_client.o:src/operations_rfs.h
src/signals_client.o:src/signals.h
src/signals_server.o:src/config.h
src/signals_server.o:src/rfsd.h
src/signals_server.o:src/signals.h
src/ssl.o:src/buffer.h
src/ssl.o:src/config.h
src/ssl.o:src/ssl.h
src/ssl_client.o:src/buffer.h
src/ssl_client.o:src/config.h
src/ssl_client.o:src/ssl_client.h
src/ssl_server.o:src/config.h
src/ssl_server.o:src/ssl_server.h
src/sug_client.o:src/config.h
src/sug_client.o:src/instance_client.h
src/sug_client.o:src/sug_client.h
src/sug_client.o:src/utils.h
src/sug_server.o:src/config.h
src/sug_server.o:src/instance_server.h
src/sug_server.o:src/passwd.h
src/sug_server.o:src/utils.h
src/utils.o:src/config.h
src/utils.o:src/sendrecv.h
rfs_nss/src/dllist.o:rfs_nss/src/dllist.h
rfs_nss/src/rfs_getnames.o:rfs_nss/src/rfs_nss.h
rfs_nss/src/rfs_nss_client.o:rfs_nss/src/rfs_nss.h
rfs_nss/src/rfs_nss_client.o:rfs_nss/src/rfs_nss.h
rfs_nss/src/rfs_nss_client.o:rfs_nss/src/rfs_nss.h
rfs_nss/src/rfs_nss_client.o:rfs_nss/src/rfs_nss_freebsd.c
rfs_nss/src/rfs_nss_client.o:rfs_nss/src/rfs_nss_solaris.c
rfs_nss/src/rfs_nss_control.o:rfs_nss/src/rfs_nss.h
rfs_nss/src/rfs_nss_server.o:rfs_nss/src/rfs_nss.h
rfs_nss/src/rfs_nss_server.o:rfs_nss/src/dllist.h
rfs_nss/src/rfs_nss_server.o:rfs_nss/src/rfs_getnames.h
src/acl_utils.o:src/acl_utils.c
src/attr_cache.o:src/attr_cache.c
src/buffer.o:src/buffer.c
src/cleanup.o:src/cleanup.c
src/command.o:src/command.c
src/crypt.o:src/crypt.c
src/data_cache.o:src/data_cache.c
src/error.o:src/error.c
src/exports.o:src/exports.c
src/fuse_rfs.o:src/fuse_rfs.c
src/id_lookup.o:src/id_lookup.c
src/id_lookup_client.o:src/id_lookup_client.c
src/instance.o:src/instance.c
src/instance_client.o:src/instance_client.c
src/instance_server.o:src/instance_server.c
src/keep_alive_client.o:src/keep_alive_client.c
src/keep_alive_server.o:src/keep_alive_server.c
src/list.o:src/list.c
src/names.o:src/names.c
src/nss_client.o:src/nss_client.c
src/nss_server.o:src/nss_server.c
src/operations_acl.o:src/operations_acl.c
src/operations.o:src/operations.c
src/operations_exports.o:src/operations_exports.c
src/operations_links.o:src/operations_links.c
src/operations_nss.o:src/operations_nss.c
src/operations_read.o:src/operations_read.c
src/operations_rfs.o:src/operations_rfs.c
src/operations_sync.o:src/operations_sync.c
src/operations_write.o:src/operations_write.c
src/passwd.o:src/passwd.c
src/path.o:src/path.c
src/resume.o:src/resume.c
src/rfs.o:src/rfs.c
src/rfsd.o:src/rfsd.c
src/rfspasswd.o:src/rfspasswd.c
src/sendrecv.o:src/sendrecv.c
src/server.o:src/server.c
src/server_handlers_acl.o:src/server_handlers_acl.c
src/server_handlers.o:src/server_handlers.c
src/server_handlers_exports.o:src/server_handlers_exports.c
src/server_handlers_links.o:src/server_handlers_links.c
src/server_handlers_nss.o:src/server_handlers_nss.c
src/server_handlers_read.o:src/server_handlers_read.c
src/server_handlers_rfs.o:src/server_handlers_rfs.c
src/server_handlers_sync.o:src/server_handlers_sync.c
src/server_handlers_write.o:src/server_handlers_write.c
src/signals.o:src/signals.c
src/signals_client.o:src/signals_client.c
src/signals_server.o:src/signals_server.c
src/sockets.o:src/sockets.c
src/ssl.o:src/ssl.c
src/ssl_client.o:src/ssl_client.c
src/ssl_server.o:src/ssl_server.c
src/sug_client.o:src/sug_client.c
src/sug_server.o:src/sug_server.c
src/utils.o:src/utils.c
