src/alloc.o:src/alloc.h
src/attr_cache.o:src/attr_cache.h
src/attr_cache.o:src/config.h
src/attr_cache.o:src/buffer.h
src/buffer.o:src/config.h
src/buffer.o:src/alloc.h
src/buffer.o:src/inet.h
src/command.o:src/command.h
src/command.o:src/config.h
src/crypt.o:src/crypt.h
src/crypt.o:src/config.h
src/exports.o:src/exports.h
src/exports.o:src/config.h
src/exports.o:src/buffer.h
src/exports.o:src/list.h
src/keep_alive_client.o:src/keep_alive_client.h
src/keep_alive_client.o:src/config.h
src/keep_alive_server.o:src/keep_alive_server.h
src/keep_alive_server.o:src/config.h
src/list.o:src/list.h
src/list.o:src/config.h
src/list.o:src/buffer.h
src/operations.o:src/operations.h
src/operations.o:src/config.h
src/operations.o:src/buffer.h
src/operations.o:src/command.h
src/operations.o:src/sendrecv.h
src/operations.o:src/attr_cache.h
src/operations.o:src/inet.h
src/operations.o:src/keep_alive_client.h
src/operations.o:src/write_cache.h
src/operations.o:src/list.h
src/operations.o:src/read_cache.h
src/operations.o:src/crypt.h
src/operations.o:#include "operations_sync.c"
src/passwd.o:src/passwd.h
src/passwd.o:src/config.h
src/passwd.o:src/list.h
src/passwd.o:src/buffer.h
src/read_cache.o:src/read_cache.h
src/read_cache.o:src/config.h
src/read_cache.o:src/buffer.h
src/rfs.o:src/config.h
src/rfs.o:src/operations.h
src/rfs.o:src/sendrecv.h
src/rfs.o:src/command.h
src/rfs.o:src/buffer.h
src/rfs.o:src/alloc.h
src/rfs.o:src/passwd.h
src/rfs.o:src/crypt.h
src/rfsd.o:src/config.h
src/rfsd.o:src/command.h
src/rfsd.o:src/signals_server.h
src/rfsd.o:src/sendrecv.h
src/rfsd.o:src/buffer.h
src/rfsd.o:src/server_handlers.h
src/rfsd.o:src/alloc.h
src/rfsd.o:src/list.h
src/rfsd.o:src/exports.h
src/rfsd.o:src/passwd.h
src/rfsd.o:src/keep_alive_server.h
src/rfspasswd.o:src/config.h
src/rfspasswd.o:src/passwd.h
src/rfspasswd.o:src/crypt.h
src/rfspasswd.o:src/signals.h
src/sendrecv.o:src/sendrecv.h
src/sendrecv.o:src/config.h
src/sendrecv.o:src/command.h
src/sendrecv.o:src/alloc.h
src/sendrecv.o:src/inet.h
src/server_handlers.o:src/server_handlers.h
src/server_handlers.o:src/config.h
src/server_handlers.o:src/command.h
src/server_handlers.o:src/sendrecv.h
src/server_handlers.o:src/buffer.h
src/server_handlers.o:src/alloc.h
src/server_handlers.o:src/rfsd.h
src/server_handlers.o:src/exports.h
src/server_handlers.o:src/list.h
src/server_handlers.o:src/passwd.h
src/server_handlers.o:src/inet.h
src/server_handlers.o:src/keep_alive_server.h
src/server_handlers.o:src/crypt.h
src/server_handlers.o:#include "server_handlers_sync.c"
src/signals.o:src/signals.h
src/signals_client.o:src/signals_client.h
src/signals_client.o:src/config.h
src/signals_client.o:src/sendrecv.h
src/signals_client.o:src/signals.h
src/signals_client.o:src/alloc.h
src/signals_client.o:src/operations.h
src/signals_server.o:src/signals_server.h
src/signals_server.o:src/config.h
src/signals_server.o:src/signals.h
src/signals_server.o:src/alloc.h
src/signals_server.o:src/rfsd.h
src/write_cache.o:src/write_cache.h
src/write_cache.o:src/config.h
src/write_cache.o:src/buffer.h
